@echo off
echo Starting Auralis Backend and Frontend...
start "Auralis Backend" cmd /k "cd backend && python -m uvicorn main:app --reload"
start "Auralis Frontend" cmd /k "cd frontend && npm start"
echo Both services starting in separate windows...
