AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Auralis Smart Contract Security Auditor Backend

Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:
  AuralisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.main.handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Timeout: 60
      MemorySize: 1024
      Events:
        ApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          USE_BEDROCK: "false"
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - bedrock:InvokeModel
            Resource: "*"

Outputs:
  AuralisApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  AuralisFunction:
    Description: "Auralis Lambda Function ARN"
    Value: !GetAtt AuralisFunction.Arn
